[package]
name = "aoc-2020"
version = "0.1.0"
authors = ["Isak Jägberg <ijagberg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
simple-grid = "0.1.1"
bitvec = "0.19.4"
itertools = "0.9.0"
